In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

Задание № 1

In [5]:
a = np.arange(12,24)
a


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание № 2

In [26]:
b1 = a.reshape(6,2)
b2 = a.reshape(4,3)
b3 = a.reshape(3,4)
b4 = a.reshape(12,1)
b5 = a.reshape(2, 6)
print(b1,'\n\n' ,b2, '\n\n', b3, '\n\n', b4, '\n\n', b5)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 

 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Задание № 3

In [42]:
c1 = a.reshape(-1,6)
c2 = a.reshape(-1, 4)
c3 = a.reshape(-1, 2)
c4 = a.reshape(3, -1)
c5 = a.reshape(12, -1)
c6 = a.reshape(6, -1)
print(c1, '\n\n', c2, '\n\n', c3, '\n\n', c4, '\n\n', c5, '\n\n', c6)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


Задание №4

In [51]:
arr = np.arange(12)
print(arr)
arr.resize(12,1)
print('\n', arr)

# В первом случае выводиться одномерный массив, во втором случае с помощью метода resize получил двумерный массив, двумерный он потому что:
# имеет индекс строк и столбцов, так же каждый массив начинается с новой строки в скобках. 
# Вывод: массив из одного столбца и 12 строк нельзя назвать одномерным. 


[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


Задание № 5

In [71]:
b = np.random.randn(3, 4)
print(b)
c = b.flatten()
print(c)

print("Размерность b: {}".format(b.ndim))
print("Размерность c: {}".format(c.ndim))

print("Size b: {}".format(b.size))
print("Size c: {}".format(c.size))



[[ 0.56321717  1.10406591  0.96799794  1.52207495]
 [ 1.34568136 -0.37412592 -1.34298384  0.15929558]
 [ 0.77401721 -0.37018826  0.03700487 -0.72000313]]
[ 0.56321717  1.10406591  0.96799794  1.52207495  1.34568136 -0.37412592
 -1.34298384  0.15929558  0.77401721 -0.37018826  0.03700487 -0.72000313]
Размерность b: 2
Размерность c: 1
Size b: 12
Size c: 12


Задание № 6

In [74]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание № 7

In [78]:
b = np.arange(20, 1, -2).reshape(1,10)
b

# РАзница в том , что масиив a одномерный , а массив b двумерный

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Задание № 8

In [95]:
a = np.zeros((2,2))
b = np.ones((3,2))

c = np.vstack((a, b))
print(c)
print("Size c: {}".format(c.size))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Size c: 10


Задание № 9

In [99]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
A = a.reshape(4, 3)
print(A)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [108]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [120]:
B = A.dot(At)
print(B)

print("Размер матрицы B: {}".format(B.shape))
# она квадратная, значит мы можем посчитать определитель

d = np.linalg.det(B)
print(d)

# Итак, если определитель квадратной матрицы не равен 0, то мы можем посчитать для неё обратную матрицу. 
# Как мы видим определитель равен 0

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы B: (4, 4)
0.0


Задание № 10

In [121]:
np.random.seed(42)


In [131]:
# Задание № 11
c = np.random.randint(0, 16, 16)
c

array([ 1,  3, 11, 14, 11,  6, 11, 12,  7, 14,  2, 13,  0,  3,  1,  7])

Задание № 12

In [137]:
C = c.reshape(4, -1)
print(C)

D = C + (B * 10)
print(D)

[[ 1  3 11 14]
 [11  6 11 12]
 [ 7 14  2 13]
 [ 0  3  1  7]]
[[  501  1403  2311  3214]
 [ 1411  5006  8611 12212]
 [ 2307  8614 14902 21213]
 [ 3200 12203 21201 30207]]


In [163]:
# определитель

d = np.linalg.det(D)
print(d)

# ранг матрицы

r = np.linalg.matrix_rank(D)
print(r)

# обратная матрица

D_inv = np.linalg.inv(D)
print(D_inv)

# проверка
print(np.allclose(np.dot(D, D_inv), np.eye(D.shape[0])))

print(np.allclose(np.dot(D_inv, D), np.eye(D.shape[0])))

143463784.00003842
4
[[-0.16667027  0.21877392  0.03494646 -0.09525302]
 [ 0.16897257 -0.23885499  0.01500189  0.06804993]
 [ 0.18246979 -0.18343588 -0.12998237  0.146025  ]
 [-0.17867281  0.20206227  0.08146653 -0.11985565]]
True
True


Задание № 13

In [164]:
D_inv = np.where(D_inv < 0, 0, 1)
print(D_inv)



[[0 1 1 0]
 [1 0 1 1]
 [1 0 0 1]
 [0 1 1 0]]


In [173]:
E = np.where(D_inv, B, C)

print(B)
print(C)
print()
print(E)

[[  50  140  230  320]
 [ 140  500  860 1220]
 [ 230  860 1490 2120]
 [ 320 1220 2120 3020]]
[[ 1  3 11 14]
 [11  6 11 12]
 [ 7 14  2 13]
 [ 0  3  1  7]]

[[   1  140  230   14]
 [ 140    6  860 1220]
 [ 230   14    2 2120]
 [   0 1220 2120    7]]
